name: 2025

on:
  push:
    branches: [ "main" ]
    paths:
      - "2025/**"
  pull_request:
    branches: [ "main" ]
    paths:
      - "2025/**"

defaults:
  run:
    working-directory: "2025"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - run: cargo fmt --check
    - run: cargo build --verbose
    - run: cargo clippy --all-targets --all-features -- -D warnings
    - run: cargo test --verbose
